apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: backend
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    semver: ">5.0.0"
  ignore: |
    /*
    !/kustomize/deployment.yaml
    !/kustomize/hpa.yaml
