apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: frontend
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: 5.0.1 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
  ignore: |
    /*
    !/kustomize/deployment.yaml
    !/kustomize/hpa.yaml
